name: tuple8
description: A Tuple implementation with a different accessing method.
version: 0.1.0+1
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.1 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
